/*
 * WHAT THIS FILE DOES, IN PLAIN WORDS
 *
 * Thirty paragraphs of everyday news, written for log 21. They are the padding a request is buried in
 * to make a long message. They say nothing about any test world: "21 long text tests.js" checks that no
 * paragraph uses the name of any thing or event in any world.
 */
module.exports = [
  'Hope you are well. Things here have been busy in the ordinary way. The neighbours finally finished their extension, so the drilling has stopped, and I can hear myself think in the mornings again. I have been trying to get up earlier and go for a walk before breakfast. Some days it works and some days it does not, but the days it works are noticeably better, so I am going to keep trying for another month and see.',
  'My sister rang on Sunday. She is thinking of changing jobs, which she has said every spring for five years, but this time she has actually applied for two. One is closer to home and one pays more, and she cannot decide which matters more to her. I told her to write both down and see which one she felt disappointed about when she crossed it out. She said that was the most annoying advice she had ever heard, which probably means it was useful.',
  'The book club met on Thursday. We were meant to discuss a long novel about a family of clockmakers, but only three of us had finished it, so we mostly talked about whether a book can be too long and still be good. I think it can, if every chapter earns its keep. Martin thinks any book over four hundred pages is showing off. We have agreed to pick something shorter next time and then argue about that instead.',
  'I finally took the bicycle in for a service. The man at the shop looked at the chain for a long time without saying anything and then asked when I had last oiled it. I said I could not remember, which he seemed to think answered his question. It rides beautifully now. I had forgotten that it is supposed to be quiet. The brakes work properly too, which I suppose I should have worried about sooner.',
  'We tried a new recipe last weekend: a lentil stew with smoked paprika and a lot of garlic. It was very good the first night and even better the second, which is the mark of a proper stew. The recipe said it served four, but that must have been four people who were not especially hungry. Next time I will double it and freeze half, because it is exactly the sort of thing you want on a tired evening.',
  'The choir is rehearsing for the winter concert already. We are doing a piece in Latin that has a very long passage where the altos hold one note while everyone else moves around them. It sounds lovely from the audience, I am told, but from inside it feels like standing still in a crowd. The conductor keeps telling us to breathe in different places from each other so the sound never stops. It is harder than it sounds.',
  'The internet at home has been unreliable for a fortnight. It works perfectly all day and then gives up at about eight in the evening, which is of course exactly when anyone wants to use it. I have spent more time on the phone to the provider than I would like to admit. They have promised an engineer visit next week. I am not holding my breath, but I have written down the reference number in three places.',
  'I went to the museum on Saturday to see the exhibition of old maps. Some of them were beautifully wrong: coastlines in the wrong spot, islands that do not exist, a sea monster drawn very carefully in an empty corner. What struck me was how confident they all looked. Nobody drawing them thought they were guessing. I stood in front of one of the whole world for twenty minutes and still did not see everything in it.',
  'My cousin is getting married in the spring, and the planning has taken over the family group chat. There are strong opinions about the menu, the music and whether children should be invited. I have said I will be happy with anything as long as there is somewhere to sit down. That was apparently the wrong thing to say, because now I have been asked to help with the seating plan.',
  'We had a quiz night at the community hall. Our team came fourth out of nine, which is our best result ever. We would have come third if anyone had known the capital of Mongolia, but none of us did. We also lost a point arguing about how many strings a harp has, which it turns out varies. The prize was a large tin of biscuits, which the winning team very kindly shared.',
  'I have started knitting again after years away from it. My first attempt was a scarf that got wider as it went along, because I kept adding stitches without noticing. It now looks like a very long triangle. I am told this is a normal beginner mistake. The second attempt is going better. I count at the end of every row now, which is slow, but it is the only way I seem to keep it straight.',
  'The weather has been strange this month: warm one day and cold the next, so nobody knows what to wear. I have taken to carrying a jumper everywhere just in case. On Tuesday I needed it at nine in the morning, did not need it at noon, and needed it again by four. The man at the bus stop and I have started a running commentary about it, which is the most we have ever said to each other.',
  'I have been listening to a podcast about the history of everyday objects. This week was about the humble paperclip, which apparently took several attempts to get right, and there are still people who think the original design was better. Last week was about umbrellas. I did not expect to find either interesting, but I have listened to every episode so far and I am slightly worried about what will happen when I run out.',
  'We went walking in the hills on the bank holiday. The weather report promised sunshine, and for once it was right. We took the long route over the ridge and stopped for lunch by an old stone barn with a view across three valleys. Coming down took longer than going up, which always surprises me. My knees have opinions about it today. We have said we will do the next stretch of the path in the autumn.',
  'The office is being redecorated, so we have all been moved to the third floor for a few weeks. It is quieter up there, and the windows face the park, which is pleasant. The downside is that the coffee machine is on the ground floor. I have walked more stairs this week than in the whole of last year. Several people have started bringing flasks from home instead, and there is now a small competition about whose is best.',
  'I finally sorted out the tax paperwork that has been sitting on the corner of the desk since March. It took one long afternoon, two cups of tea and a lot of muttering, but it is done. It was not nearly as bad as I had made it in my head. There is probably a lesson there about how dreading something is often worse than doing it, but I expect I will ignore it again next year.',
  'A pair of robins has been visiting the feeder every morning. One is bolder than the other and will sit on the fence while I am standing at the window. The other waits until I have gone. I have started putting out a little extra in the colder mornings. I know it is silly to feel pleased when they turn up, but I do, and it is a nice way to start the day.',
  'The film club showed an old black and white comedy on Friday. I had not expected much, but it was genuinely funny, with a long scene in a hotel corridor where people keep missing each other by seconds. The timing was perfect. Afterwards we talked about how hard that sort of thing must have been to film before any of the modern tricks. Half the audience stayed for tea and biscuits, which is unusual.',
  'I have been reading about the history of the town. It turns out the high street used to be the market square, and the old inn was where traders stayed overnight. The building is still there, though it is a bank now. There is a small plaque on the side that I must have walked past a thousand times without reading. I have started noticing plaques everywhere since, and there are far more than I thought.',
  'My neighbour has taken up the trumpet. He is very enthusiastic and practises every evening between six and seven. He is getting better, slowly. At first it sounded like a duck in distress, and now it sounds more like a duck that has made its peace with things. I have decided to be encouraging about it. He has promised to learn one tune all the way through by Christmas, and I am curious which one it will be.',
  'I bought a new kettle, because the old one had started making an alarming noise before it switched off. The new one is very quiet and has a little light that changes colour as the water heats. It seems a bit unnecessary, but I have grown fond of it. The old one is in the cupboard in case the new one lets me down, although I cannot imagine actually going back to it.',
  'We have been clearing out the loft. It is remarkable what accumulates when nobody looks. We found three broken chairs, a folder of photographs from the nineteen seventies, a tennis racket with no strings and a very large jigsaw puzzle that nobody remembers buying. The photographs are wonderful and I have been going through them slowly in the evenings. The jigsaw is now on the dining table, and we eat in the kitchen.',
  'Our local bakery has started making sourdough on Saturdays. It sells out by half past nine, so there is now a small queue at eight on Saturday mornings, full of people pretending they just happened to be passing. I have joined it twice. The bread is excellent, with a thick crust that makes a proper noise when you cut it. The baker says she might do Wednesdays as well if the demand holds.',
  'My old school friend came to stay for the weekend. We had not met up in six years, but within ten minutes it was as if no time had passed at all. We stayed up far too late talking about people we used to know and what became of them. She is thinking of moving back to this part of the country, which would be lovely. I have promised to show her the new library when she visits again.',
  'I have been learning a little Spanish on my phone, ten minutes a day. The app is very pleased with me and keeps sending congratulations, which I find both encouraging and faintly embarrassing. I can now order coffee, ask where the station is and describe the colour of my imaginary cat. Real conversation is still a long way off, but I have started understanding the odd word in songs, which feels like progress.',
  'The allotment association held its annual meeting, and I went along for the first time as a guest. There was a forty minute discussion about the shared shed and whose turn it is to fix the gutter. It was more gripping than it sounds. Everyone had clearly been having the same conversation for years, and there were alliances and old grudges I could only guess at. I left with a jar of chutney and a lot of questions.',
  'The car needed a new battery, and of course it chose the coldest morning of the month to tell me. A very cheerful man from the breakdown service arrived within the hour and had it running in ten minutes. He said this happens to half his customers every autumn. I have now put a reminder in my calendar for next year, though I suspect I will ignore that one too when the time comes.',
  'I went to a talk at the library about the night sky. The speaker brought a telescope and, when the clouds cleared, let everyone take a turn looking at a planet. It was a tiny, sharp little disc with stripes across it, and I think everyone in the queue said "oh" out loud when it was their turn. I had looked at pictures all my life, but looking at it for myself was different. I am thinking of buying binoculars.',
  'We have started a small tradition of cooking something from a different country every Friday. So far we have done a curry, a paella, a Hungarian goulash and a Japanese curry that was quite different from the first one. The results have ranged from very good to edible. The rule is that nobody is allowed to complain about the washing up, which is the hardest part to keep to.',
  'That is most of the news from here. The days are getting shorter and there is a proper chill in the evenings now, so the thick curtains have gone back up. I have been meaning to write for weeks, and I am glad to have finally sat down to do it. Let me know how things are with you, and whether you are still thinking of visiting in the new year. We would love to see you.',
];
