#!/usr/bin/env python3
"""Render docs/kernel.md from the boundary catalogue in tests/kernel_boundaries.py.

Standard library only. The catalogue is the source; the document is derived, and
tests/test_kernel.py refuses a document that differs from what this renders.
"""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "docs" / "kernel.md"

PREAMBLE = """# What each check cannot see, point by point

*Generated by `python tools/kernel_table.py` from `tests/kernel_boundaries.py`; `tests/test_kernel.py` holds every row and refuses a document that has drifted from the catalogue. Do not edit by hand.*

Every check in the machine is invariant under some transformation of what it reads: change the reply, the document, or the record that way and the verdict does not move. That set is the check's kernel, the class of things it cannot do. A general statement of the class would be a conjecture; what can be stated exactly is a boundary point: one transformation the verdict moves under, as small as it can be made, beside one it does not, as close to the first as it can be brought. Each row below is such a point, and each is asserted both ways by the suite: the moved verdict differs from the base, the unmoved one equals it. A row whose first column is empty names a check that nothing moves.

The rows are read against a survival. A reply that passed every check passed exactly these checks, with exactly these blind spots, on these records; the machine never promotes, and this table is the reason stated in full. A point that begins to fail because a check now sees what the row says it cannot is the boundary moving, and the row is rewritten in the same change.

Two rows were written as boundaries and then decided to be defects, on the committed records: P-02 (nine cycle replies were scored on a quoted draft rather than the corrected answer that followed it, H40) and G-08 (the containment check did not normalise whitespace where the occurrence check did, H41); each row now states the boundary after the change, and its note says what moved. One row records a boundary that is arguably a defect and is kept until decided: V-01 (a closed-list item is found on a page by substring). P-07 records a limit kept deliberately.
"""


def _cell(text: str | None) -> str:
    return "" if text is None else text.replace("|", "\\|").replace("\n", " ")


def render(points) -> str:
    lines = [PREAMBLE, "| Point | Check | The verdict moves under | The verdict is unchanged under | Note |", "|---|---|---|---|---|"]
    for point in points:
        lines.append(f"| {point.point} | {_cell(point.check)} | {_cell(point.moves_under)} | {_cell(point.unchanged_under)} | {_cell(point.note)} |")
    lines.append("")
    lines.append(f"{len(points)} points. A survival is a survival of exactly these checks, with exactly these blind spots, on these records.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    sys.path.insert(0, str(ROOT / "src"))
    sys.path.insert(0, str(ROOT / "tests"))
    import kernel_boundaries

    TARGET.write_text(render(kernel_boundaries.boundaries()), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
